### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by jonthegeek** [colearendt/shinycookie#10]
Is this project still active? If not, is there a better way to deal with cookies in Shiny?

**Comment by daattali** [comment]
Did you ever get the answer to this?

**Comment by jonthegeek** [comment]
@daattali I did not. I ended up dealing with cookies more-directly in the place where I wanted to use them (by using [John Coene's book](https://book.javascript-for-r.com/shiny-cookies.html) as a guide).

**Comment by jonthegeek** [comment]
@daattali I don't remember whether I tagged you when I made a separate package for cookies, but [here it is](https://cran.r-project.org/package=cookies).
